server:
  port: 8080
  servlet:
    context-path: /

spring:
  # 数据源配置
  datasource:
    # 默认使用H2数据库，可通过环境变量覆盖为MySQL
    url: ${DB_URL:jdbc:h2:file:./database/app_update_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    
  # H2数据库控制台配置(仅开发环境使用)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
      settings:
        web-allow-others: true
        
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

# 应用自定义配置
app:
  # APK文件上传存储路径
  upload-path: ${UPLOAD_PATH:./apk_uploads/}
  # H2数据库文件路径(仅当使用H2时有效)
  db-path: ${DB_PATH:./database/}
  # 服务器基础URL，用于生成下载链接
  server-base-url: ${SERVER_BASE_URL:http://localhost:8080}
  # 管理API的密钥
  admin:
    api-key: ${ADMIN_API_KEY:your-secret-api-key}

# 日志配置
logging:
  level:
    com.dongshiqian.appupdate: ${LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAM_LOG_LEVEL:TRACE}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
# 生产环境配置示例
---
spring:
  config:
    activate:
      on-profile: prod
  # 生产环境数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/app_update_db?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:app_update}
    password: ${DB_PASSWORD:your_mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  # 生产环境禁用H2控制台
  h2:
    console:
      enabled: false

# 生产环境日志配置
logging:
  level:
    com.dongshiqian.appupdate: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: logs/app-update-server.log
    max-size: 100MB
    max-history: 30 